@startuml 
    title Туроператор
    actor Турист
    participant Туроператор
    participant Гостиница
    
    Турист -> Туроператор: Найти гостиницу (Параметры поиска)
    note right 
        Параметры поиска: 
        - Город 
        - Дата заезда
        - Дата выезда 
        - Количество взрослых 
        - Количество детей
    end note
    Туроператор --> Турист: Результаты поиска

    Турист -> Туроператор: Выбрать гостиницу()
    Туроператор --> Турист: Форма бронирования

    Турист -> Туроператор: Забронировать гостиницу (Данные бронирования)
    note right 
        Параметры бронирования: 
        - Выбранный номер
        - Паспортные данные
        - Данные оплаты
    end note
    Туроператор -\ Гостиница: Отправить заявку на бронирование()
    Туроператор --> Турист: "Заявка на бронирования принята"
    
    alt успешное бронирование
    Гостиница --\ Туроператор: "Номер забронирован"
    Туроператор --\ Турист: "Заявка на бронирование исполнена"
    else нет свободных номеров
    Гостиница --\ Туроператор: "Нет свободных номеров"
    Туроператор --\ Турист: "Не удалоись исполнить бронироание"
    end
    
    Турист -\ Туроператор: Оплатить бронь(Параметры оплаты)
    Туроператор -> Туроператор: Обработать оплату(Параметры оплаты)
    alt успешная оплата
    Туроператор --\ Турист: "Бронь оплачена" 
    else не удалось оплатить
    Туроператор --\ Турист: "Не удалось оплатить бронь"
    end
@enduml