@startuml Оплатить бронирование
    title Оплатить бронирование
    actor Турист
    participant Туроператор
    participant Платежка as "Платежный шлюз"
    
    Турист -\ Туроператор: Оплатить бронь(Параметры оплаты)
    note right
        Параметры оплаты:
        - номер карты
        - срок действия карты
        - имя владельца
        - CVV код
    end note
    Туроператор -\ Платежка: Произвести оплату(Параметры оплаты)
    alt успешная оплата
    Платежка --\ Туроператор: "Оплачено"
    Туроператор --\ Турист: "Бронь оплачена" 
    else не удалось оплатить
    Платежка --\ Туроператор: "Не удалось оплатить"
    Туроператор --\ Турист: "Не удалось оплатить бронь"
    end

@enduml